(() => {
 const prefix='guild-rich-v1:',formats=['bold','italic','underline','strike','header','list','blockquote','link','image'];
 function decode(content){if(!String(content).startsWith(prefix))return null;try{const value=JSON.parse(content.slice(prefix.length));return Array.isArray(value.ops)?value:null;}catch{return null;}}
 function attributes(value={}){const result={};for(const name of ['bold','italic','underline','strike','blockquote'])if(value[name]===true)result[name]=true;if([1,2,3].includes(value.header))result.header=value.header;if(['ordered','bullet'].includes(value.list))result.list=value.list;if(typeof value.link==='string'){try{const url=new URL(value.link);if(['https:','http:'].includes(url.protocol))result.link=url.href;}catch{}}return result;}
 function contentOps(content,images,url){const rich=decode(content);if(!rich)return [{insert:String(content || '')+'\n'},...images.flatMap(image=>[{insert:{image:url(image)}},{insert:'\n'}])];return rich.ops.flatMap(op=>{if(typeof op.insert==='string')return [{insert:op.insert,attributes:attributes(op.attributes)}];const match=String(op.insert?.image || '').match(/^guild-image:(\d+)$/);return match && images[Number(match[1])]? [{insert:{image:url(images[Number(match[1])])}}]:[];});}
 function editor(form,{status,content='',images=[],url,encode}){
  const textarea=form.elements.content;textarea.hidden=true;textarea.required=false;
  const wrapper=document.createElement('div');wrapper.className='rich-editor';textarea.after(wrapper);
  const toolbar=document.createElement('div');toolbar.className='rich-toolbar';
  for(const [name,title,value] of [['bold','굵게'],['italic','기울임'],['underline','밑줄'],['list','글머리 기호','bullet'],['list','번호 목록','ordered'],['blockquote','인용'],['link','링크'],['clean','서식 지우기']]){const button=document.createElement('button');button.type='button';button.className='ql-'+name;button.title=title;button.setAttribute('aria-label',title);if(value)button.value=value;toolbar.append(button);}
  const surface=document.createElement('div');wrapper.append(toolbar,surface);const quill=new Quill(surface,{theme:'snow',formats,modules:{toolbar,history:{userOnly:true}}});quill.root.setAttribute('role','textbox');quill.root.setAttribute('aria-label','내용');quill.root.setAttribute('aria-multiline','true');quill.root.spellcheck=false;
  const known=new Map();let work=Promise.resolve(),generation=0,locked=false,failed='';
  function load(text,pictures){generation++;known.clear();for(const image of pictures)known.set(url(image),image);quill.setContents({ops:contentOps(text,pictures,url)},'silent');quill.history.clear();textarea.value=text;failed='';}
  load(content,images);
  function serialize(){const pictures=[],ops=[];for(const op of quill.getContents().ops){if(typeof op.insert==='string'){ops.push({insert:op.insert,...(op.attributes?{attributes:attributes(op.attributes)}:{})});continue;}const image=known.get(op.insert?.image);if(!image)throw new Error('사진을 다시 붙여넣어주세요.');ops.push({insert:{image:'guild-image:'+pictures.length}});pictures.push(image.id?{id:image.id}:{mime:image.mime,data:image.data});}
   if(pictures.length>5)throw new Error('사진은 최대 5장까지 삽입할 수 있습니다.');if(!quill.getText().trim() && !pictures.length)throw new Error('내용이나 사진을 추가해주세요.');const serialized=prefix+JSON.stringify({ops});if(serialized.length>5000)throw new Error('글이 너무 깁니다. 내용을 조금 줄여주세요.');textarea.value=serialized;return {content:serialized,images:pictures};}
  async function insert(files){if(locked)return;failed='';const current=generation,selection=quill.getSelection(true) || {index:Math.max(0,quill.getLength()-1),length:0};
   // A live marker keeps the paste position stable while the screenshot is encoded.
   const marker='\uFFFC';quill.deleteText(selection.index,selection.length,'user');quill.insertText(selection.index,marker,'user');let markerIndex=selection.index;
   const track=(delta)=>{markerIndex=delta.transformPosition(markerIndex,false);};quill.on('text-change',track);
   work=work.then(async()=>{try{for(const file of files){if(current!==generation)return;const count=quill.getContents().ops.filter(op=>typeof op.insert!=='string').length;if(count>=5)throw new Error('사진은 최대 5장까지 삽입할 수 있습니다.');status.textContent='사진을 준비 중입니다.';const image=await encode(file);if(current!==generation)return;const src=`data:${image.mime};base64,${image.data}`;known.set(src,image);quill.off('text-change',track);quill.insertEmbed(markerIndex,'image',src,'api');markerIndex++;quill.insertText(markerIndex,'\n','api');markerIndex++;quill.on('text-change',track);}status.textContent='';}catch(error){failed=error.message;status.textContent=failed;}finally{quill.off('text-change',track);if(current===generation){const text=quill.getText(markerIndex,1);if(text===marker)quill.deleteText(markerIndex,1,'api');quill.setSelection(Math.min(markerIndex,quill.getLength()-1),0,'silent');}}});return work;
  }
  quill.root.addEventListener('paste',event=>{const files=[...event.clipboardData.items].filter(item=>item.kind==='file' && item.type.startsWith('image/')).map(item=>item.getAsFile()).filter(Boolean);if(files.length){event.preventDefault();event.stopImmediatePropagation();insert(files);}},true);
  quill.root.addEventListener('drop',event=>{const files=[...event.dataTransfer.files].filter(file=>file.type.startsWith('image/'));if(files.length){event.preventDefault();event.stopImmediatePropagation();insert(files);}},true);
  quill.clipboard.addMatcher('IMG',()=>new (Quill.import('delta'))());
  quill.on('text-change',()=>{try{serialize();}catch{}});
  return {quill,async values(){await work;if(failed)throw new Error(failed);const result=serialize();locked=true;quill.enable(false);toolbar.querySelectorAll('button').forEach(button=>button.disabled=true);return result;},unlock(){locked=false;quill.enable(true);toolbar.querySelectorAll('button').forEach(button=>button.disabled=false);},reset(text='',pictures=[]){load(text,pictures);this.unlock();}};
 }
 function render(parent,content,images,url){if(!decode(content))return false;const node=document.createElement('div');node.className='rich-content';parent.append(node);const view=new Quill(node,{readOnly:true,formats,modules:{toolbar:false},theme:'snow'});view.setContents({ops:contentOps(content,images,url)},'silent');view.root.removeAttribute('contenteditable');for(const image of view.root.querySelectorAll('img')){image.loading='lazy';image.decoding='async';image.alt='본문 사진';}return true;}
 function text(content){const value=decode(content);return value?value.ops.map(op=>typeof op.insert==='string'?op.insert:'').join(''):content;}
 window.GuildRich={editor,render,text};
})();
